# Generated by Django 5.1 on 2024-11-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_image_images_imag_created_62db75_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
